"""
Email delivery via SendGrid.
Sends the daily literature digest as an HTML email.
"""

import os
import json
import datetime
import urllib.request


SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
FROM_EMAIL       = os.environ.get("FROM_EMAIL", "alerts@yourdomain.com")
FROM_NAME        = os.environ.get("FROM_NAME", "Radiology Lit Agent")
TO_EMAIL         = os.environ["TO_EMAIL"]
TO_EMAIL_2       = os.environ.get("TO_EMAIL_2", "")


EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{ font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a1a; background: #f9f9f9; }}
  .header {{ background: #1a3a5c; color: white; padding: 20px 24px; border-radius: 8px 8px 0 0; }}
  .header h1 {{ margin: 0; font-size: 20px; font-weight: 600; }}
  .header p {{ margin: 4px 0 0; font-size: 13px; opacity: 0.8; }}
  .content {{ background: white; padding: 24px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px; }}
  h3 {{ margin-top: 24px; margin-bottom: 6px; font-size: 15px; }}
  h3 a {{ color: #1a3a5c; text-decoration: none; }}
  h3 a:hover {{ text-decoration: underline; }}
  p {{ margin: 6px 0 12px; font-size: 14px; line-height: 1.6; color: #333; }}
  .source-badge {{ display: inline-block; font-size: 11px; padding: 2px 8px; border-radius: 12px; background: #e8f0fe; color: #1a3a5c; font-family: monospace; margin-left: 8px; vertical-align: middle; }}
  .footer {{ font-size: 12px; color: #888; margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px; }}
</style>
</head>
<body>
  <div class="header">
    <h1>📄 Radiology AI Literature Digest</h1>
    <p>{date} · {count} new paper{plural}</p>
  </div>
  <div class="content">
    {body}
    <div class="footer">
      Generated by your literature monitoring agent · Sources: PubMed &amp; arXiv<br>
      Topics: radiology report generation, LLMs, automated reporting
    </div>
  </div>
</body>
</html>
"""


def send_digest(html_body: str, paper_count: int) -> bool:
    """Send the digest email via SendGrid. Returns True on success."""
    today   = datetime.date.today().strftime("%B %d, %Y")
    plural  = "s" if paper_count != 1 else ""
    html    = EMAIL_TEMPLATE.format(
        date=today,
        count=paper_count,
        plural=plural,
        body=html_body,
    )
    subject = f"Radiology AI Digest — {today} ({paper_count} new paper{plural})"

    payload = json.dumps({
        "personalizations": [{"to": [e for e in [{"email": TO_EMAIL}, {"email": TO_EMAIL_2} if TO_EMAIL_2 else None] if e]}],
        "from": {"email": FROM_EMAIL, "name": FROM_NAME},
        "subject": subject,
        "content": [{"type": "text/html", "value": html}],
    }).encode()

    req = urllib.request.Request(
        "https://api.sendgrid.com/v3/mail/send",
        data=payload,
        headers={
            "Authorization": f"Bearer {SENDGRID_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            status = resp.status
        if status == 202:
            print(f"✓ Email sent to {TO_EMAIL} ({paper_count} papers)")
            return True
        else:
            print(f"✗ Unexpected status: {status}")
            return False
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"✗ SendGrid error {e.code}: {body}")
        return False


def send_no_results_email() -> None:
    """Send a brief 'nothing new today' email."""
    today = datetime.date.today().strftime("%B %d, %Y")
    send_digest("<p>No new papers matched your topics today. Check back tomorrow!</p>", 0)


if __name__ == "__main__":
    # Test with dummy content
    test_html = "<h3><a href='https://arxiv.org'>Test Paper Title</a></h3><p>This is a test summary.</p>"
    print("Sending test email...")
    send_digest(test_html, 1)
