import os
import json
import datetime
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

GMAIL_USER = os.environ["GMAIL_USER"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]
TO_EMAIL = os.environ["TO_EMAIL"]
TO_EMAIL_2 = os.environ.get("TO_EMAIL_2", "")

EMAIL_TEMPLATE = """<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
body{font-family:Georgia,serif;max-width:680px;margin:0 auto;padding:24px;color:#1a1a1a;background:#f9f9f9}
.header{background:#1a3a5c;color:white;padding:20px 24px;border-radius:8px 8px 0 0}
.header h1{margin:0;font-size:20px}
.header p{margin:4px 0 0;font-size:13px;opacity:.8}
.content{background:white;padding:24px;border:1px solid #e0e0e0;border-top:none;border-radius:0 0 8px 8px}
h2{color:#1a3a5c;border-bottom:1px solid #eee;padding-bottom:4px}
h3{margin-top:16px;margin-bottom:4px;font-size:15px}
h3 a{color:#1a3a5c;text-decoration:none}
p{margin:4px 0 12px;font-size:14px;line-height:1.6;color:#333}
small{color:#888;font-size:12px}
.footer{font-size:12px;color:#888;margin-top:24px;border-top:1px solid #eee;padding-top:12px}
</style>
</head>
<body>
<div class="header">
<h1>Radiology AI Literature Digest</h1>
<p>{date} &middot; {count} new paper{plural}</p>
</div>
<div class="content">
{body}
<div class="footer">Generated by your literature monitoring agent &middot; Sources: PubMed &amp; arXiv</div>
</div>
</body>
</html>"""


def send_digest(html_body, paper_count, part=""):
    today = datetime.date.today().strftime("%B %d, %Y")
    plural = "s" if paper_count != 1 else ""
    html = EMAIL_TEMPLATE.replace("{date}", today).replace("{count}", str(paper_count)).replace("{plural}", plural).replace("{body}", html_body)
    subject = "Radiology AI Digest - " + today + " (" + str(paper_count) + " new paper" + plural + ")" + part

    recipients = [TO_EMAIL]
    if TO_EMAIL_2:
        recipients.append(TO_EMAIL_2)

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = GMAIL_USER
        msg["To"] = ", ".join(recipients)
        msg.attach(MIMEText(html, "html"))

        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, recipients, msg.as_string())

        print("Email sent to " + str(len(recipients)) + " recipient(s) (" + str(paper_count) + " papers)")
        return True
    except Exception as e:
        print("Email error: " + str(e))
        return False
